name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Create run script
      run: |
        echo @echo off > run_app.bat
        echo set STREAMLIT_SERVER_PORT=8501 >> run_app.bat
        echo streamlit run app.py >> run_app.bat
        
    - name: Build package
      run: |
        pip install pyinstaller
        pyinstaller --onefile --add-data "app.py;." --add-data "requirements.txt;." --log-level DEBUG app.py
        echo "=== Build Artifacts ==="
        ls -R dist/
        cp run_app.bat dist/
        
    - name: Verify build
      run: |
        if [ ! -f "dist/app.exe" ]; then
          echo "::error::Build failed - app.exe not found!"
          exit 1
        fi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-web-app
        path: |
          dist/run_app.exe
          requirements.txt
